name: "build-test"
  
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: |
        ps -ef | grep top
    - run: |
        ls -lisa 
