name: "build-test"
  
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: |
        pwd
    - run: |
        ls -lisa
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
            build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
    - name: Deploy
      run: aws s3 cp build s3://shasta-webapp --recursive 
