name: "build-test"
  
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [labeled]
  push:
    branches:
      - main
env: 
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: kubernetes-github-actions    

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        ps -ef | grep top
    - name: Deploy
      env:
        ECR_REGISTRY: abcdef
      run: |
        export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}
        export IMAGE_TAG=${{ env.ECR_REGISTRY }}
        envsubst < abcd.yaml
